apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: shopping
  labels:
    app: nginx
spec:
  replicas: 4
  selector:
    matchLabels:
      webserver: nginx
  template:
    metadata:
      labels:
        webserver: nginx
    spec:
      containers:
      - image: 192.168.84.250:8081/docker-registry/nginx:1.29
        name: nginx-container-01
      - image: 192.168.84.250:8081/docker-registry/nginx:1.28
        name: nginx-container-02
